### ISSUE TITLE
CDeep3M-V2 installation fails in Google Colab

### ISSUE THREAD

**Issue by tldirkse-nl** [haberlmatt/cdeep3m-colab#3]
The code cell for the installation of CDeep3M-V2 gives errors in Google Colab. The provided notebooks on GitHub (e.g. Prediction GUI) do not seem to work anymore?

![image](https://user-images.githubusercontent.com/12046273/110330862-9c9f6c80-801e-11eb-9c88-32431902937b.png)

**Comment by haberlmatt** [comment]
should be fixed now
